// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsMx-0akV9N3O0EUjhDr3wO8-9aQ1eWNQ',
    appId: '1:734651446656:android:6431363997151237073d65',
    messagingSenderId: '734651446656',
    projectId: 'benedicti',
    databaseURL: 'https://benedicti-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'benedicti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrOGHkBnaIRQR99oEaBKkzKqfAYjEBzV4',
    appId: '1:734651446656:ios:7dfa8a4dcb06b7a5073d65',
    messagingSenderId: '734651446656',
    projectId: 'benedicti',
    databaseURL: 'https://benedicti-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'benedicti.appspot.com',
    iosClientId: '734651446656-1ttt669qn6p9s5q897l79lel5als3t40.apps.googleusercontent.com',
    iosBundleId: 'com.benedict.benedict',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrOGHkBnaIRQR99oEaBKkzKqfAYjEBzV4',
    appId: '1:734651446656:ios:7dfa8a4dcb06b7a5073d65',
    messagingSenderId: '734651446656',
    projectId: 'benedicti',
    databaseURL: 'https://benedicti-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'benedicti.appspot.com',
    iosClientId: '734651446656-1ttt669qn6p9s5q897l79lel5als3t40.apps.googleusercontent.com',
    iosBundleId: 'com.benedict.benedict',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp-fG6ZFvkhrlLCzpVDtS4wJtCqdJkXTA',
    appId: '1:734651446656:web:e47658cb8eca32b4073d65',
    messagingSenderId: '734651446656',
    projectId: 'benedicti',
    authDomain: 'benedicti.firebaseapp.com',
    databaseURL: 'https://benedicti-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'benedicti.appspot.com',
    measurementId: 'G-QJXB39HHWD',
  );
}
